package com.lhh.vista.wbservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-11T11:25:31.674+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "WSVistaVoucher", 
                  wsdlLocation = "http://123.207.174.230/WSVistaVoucher/WSVistaVoucher.wsdl?wsdl",
                  targetNamespace = "http://vista.co.nz/webservices/WSVistaVoucher") 
public class WSVistaVoucher extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://vista.co.nz/webservices/WSVistaVoucher", "WSVistaVoucher");
    public final static QName WSVistaVoucherSoap = new QName("http://vista.co.nz/webservices/WSVistaVoucher", "WSVistaVoucherSoap");
    public final static QName WSVistaVoucherSoap12 = new QName("http://vista.co.nz/webservices/WSVistaVoucher", "WSVistaVoucherSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://123.207.174.230/WSVistaVoucher/WSVistaVoucher.wsdl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSVistaVoucher.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://123.207.174.230/WSVistaVoucher/WSVistaVoucher.wsdl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSVistaVoucher(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSVistaVoucher(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSVistaVoucher() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSVistaVoucher(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSVistaVoucher(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSVistaVoucher(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WSVistaVoucherSoap
     */
    @WebEndpoint(name = "WSVistaVoucherSoap")
    public WSVistaVoucherSoap getWSVistaVoucherSoap() {
        return super.getPort(WSVistaVoucherSoap, WSVistaVoucherSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSVistaVoucherSoap
     */
    @WebEndpoint(name = "WSVistaVoucherSoap")
    public WSVistaVoucherSoap getWSVistaVoucherSoap(WebServiceFeature... features) {
        return super.getPort(WSVistaVoucherSoap, WSVistaVoucherSoap.class, features);
    }


    /**
     *
     * @return
     *     returns WSVistaVoucherSoap
     */
    @WebEndpoint(name = "WSVistaVoucherSoap12")
    public WSVistaVoucherSoap getWSVistaVoucherSoap12() {
        return super.getPort(WSVistaVoucherSoap12, WSVistaVoucherSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSVistaVoucherSoap
     */
    @WebEndpoint(name = "WSVistaVoucherSoap12")
    public WSVistaVoucherSoap getWSVistaVoucherSoap12(WebServiceFeature... features) {
        return super.getPort(WSVistaVoucherSoap12, WSVistaVoucherSoap.class, features);
    }

}
