package com.lhh.vista.wbservice;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-01-11T11:25:31.656+08:00
 * Generated source version: 3.2.1
 * 
 */
public final class WSVistaVoucherSoap_WSVistaVoucherSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://vista.co.nz/webservices/WSVistaVoucher", "WSVistaVoucher");

    private WSVistaVoucherSoap_WSVistaVoucherSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSVistaVoucher.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSVistaVoucher ss = new WSVistaVoucher(wsdlURL, SERVICE_NAME);
        WSVistaVoucherSoap port = ss.getWSVistaVoucherSoap12();  
        
        {
        System.out.println("Invoking executecmd...");
        java.lang.String _executecmd_syssettings = "<proplist><prop name=\"ID\" value=\"\"/><prop name=\"SERVICEURL\" value=\"http://123.207.174.230/WSVistaVoucher/WSVistaVoucher.asmx\"/><prop name=\"SERVICETIMEOUTSECS\" value=\"30\"/><prop name=\"CHECKSUMCODE\" value=\"SKIP\"/><prop name=\"TAXMODE\" value=\"I\"/><prop name=\"CASEINSENSITIVEVOUCHERCODES\" value=\"Y\"/><prop name=\"VOIDSALEONREFUND\" value=\"N\"/><prop name=\"LOGGINGLEVEL\" value=\"3\"/><prop name=\"HOSERVER\" value=\"\"/><prop name=\"MODE\" value=\"ONLINE\"/></proplist>";
        java.lang.String _executecmd_cmddataVal = "<proplist><prop name=\"ID\" value=\"122100000002\"/><prop name=\"REQUESTACTION\" value=\"16\"/><prop name=\"DUPLICATENO\" value=\"0\"/><prop name=\"VOUCHERCODE\" value=\"1221\"/><prop name=\"SERIALNO\" value=\"02\"/><prop name=\"ISCONNECTED\" value=\"Y\"/><prop name=\"LOCALDATETIME\" value=\"20140831123227\"/></proplist>";
        javax.xml.ws.Holder<java.lang.String> _executecmd_cmddata = new javax.xml.ws.Holder<java.lang.String>(_executecmd_cmddataVal);
        java.lang.String _executecmd_returndataVal = "<proplist></proplist>";
        javax.xml.ws.Holder<java.lang.String> _executecmd_returndata = new javax.xml.ws.Holder<java.lang.String>(_executecmd_returndataVal);
        javax.xml.ws.Holder<java.lang.Integer> _executecmd_executecmdResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.executecmd(_executecmd_syssettings, _executecmd_cmddata, _executecmd_returndata, _executecmd_executecmdResult);

        System.out.println("executecmd._executecmd_cmddata=" + _executecmd_cmddata.value);
        System.out.println("executecmd._executecmd_returndata=" + _executecmd_returndata.value);
        System.out.println("executecmd._executecmd_executecmdResult=" + _executecmd_executecmdResult.value);

        }
        {
        System.out.println("Invoking batchimporttransactions...");
        java.lang.String _batchimporttransactions_xmlMsg = "";
        java.lang.String _batchimporttransactions_responseMessageVal = "";
        javax.xml.ws.Holder<java.lang.String> _batchimporttransactions_responseMessage = new javax.xml.ws.Holder<java.lang.String>(_batchimporttransactions_responseMessageVal);
        javax.xml.ws.Holder<java.lang.Integer> _batchimporttransactions_batchimporttransactionsResult = new javax.xml.ws.Holder<java.lang.Integer>();
        port.batchimporttransactions(_batchimporttransactions_xmlMsg, _batchimporttransactions_responseMessage, _batchimporttransactions_batchimporttransactionsResult);

        System.out.println("batchimporttransactions._batchimporttransactions_responseMessage=" + _batchimporttransactions_responseMessage.value);
        System.out.println("batchimporttransactions._batchimporttransactions_batchimporttransactionsResult=" + _batchimporttransactions_batchimporttransactionsResult.value);

        }

        System.exit(0);
    }

}
